/**
 * HomeRealResultsSection Component
 *
 * Showcases real results from each of the 3 AI products with specific
 * ROI numbers and success metrics.
 */

import React from 'react';
import { TrendingUp, DollarSign, Users, Clock } from 'lucide-react';

const HomeRealResultsSection: React.FC = () => {
  return (
    <div className="py-16 md:py-24 bg-white">
      <div className="container mx-auto px-4">
        <div className="max-w-7xl mx-auto">
          {/* Section Header */}
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-6 text-gray-900">
              Real Results from Real Businesses
            </h2>
            <p className="text-xl text-gray-700 max-w-3xl mx-auto">
              Not hypothetical. Not projections. Actual revenue generated by our AI systems.
            </p>
          </div>

          {/* Results Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-12">
            {/* Dealership AI Results */}
            <div className="bg-gradient-to-br from-primary/5 to-accent2/5 rounded-2xl p-8 border-2 border-primary/20 shadow-lg hover:shadow-xl transition-all">
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-2xl font-bold text-gray-900">Dealership AI</h3>
                <div className="bg-primary/10 p-3 rounded-xl">
                  <TrendingUp className="h-8 w-8 text-primary" />
                </div>
              </div>

              <p className="text-gray-700 mb-6 font-semibold">
                Mid-size auto dealership in Quebec
              </p>

              <div className="space-y-6">
                <div className="bg-white rounded-xl p-6 border border-primary/20">
                  <div className="flex items-center gap-3 mb-2">
                    <DollarSign className="h-6 w-6 text-primary" />
                    <span className="text-3xl font-bold text-primary">$31K</span>
                  </div>
                  <p className="text-gray-700 font-semibold">Additional revenue per month</p>
                  <p className="text-gray-600 text-sm mt-1">From after-hours leads alone</p>
                </div>

                <div className="bg-white rounded-xl p-6 border border-primary/20">
                  <div className="flex items-center gap-3 mb-2">
                    <Users className="h-6 w-6 text-primary" />
                    <span className="text-3xl font-bold text-primary">35</span>
                  </div>
                  <p className="text-gray-700 font-semibold">Leads captured monthly</p>
                  <p className="text-gray-600 text-sm mt-1">That would have been lost</p>
                </div>

                <div className="bg-white rounded-xl p-6 border border-primary/20">
                  <div className="flex items-center gap-3 mb-2">
                    <Clock className="h-6 w-6 text-primary" />
                    <span className="text-3xl font-bold text-primary">2 AM</span>
                  </div>
                  <p className="text-gray-700 font-semibold">Peak engagement time</p>
                  <p className="text-gray-600 text-sm mt-1">When showroom is closed</p>
                </div>
              </div>

              <div className="mt-6 p-4 bg-primary/10 rounded-lg border border-primary/20">
                <p className="text-center font-bold text-gray-800">
                  ROI: 847% in first 6 months
                </p>
              </div>
            </div>

            {/* Ecommerce AI Results */}
            <div className="bg-gradient-to-br from-primary/5 to-accent2/5 rounded-2xl p-8 border-2 border-primary/20 shadow-lg hover:shadow-xl transition-all">
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-2xl font-bold text-gray-900">Ecommerce AI</h3>
                <div className="bg-primary/10 p-3 rounded-xl">
                  <TrendingUp className="h-8 w-8 text-primary" />
                </div>
              </div>

              <p className="text-gray-700 mb-6 font-semibold">
                Fashion e-commerce store, $2M annual revenue
              </p>

              <div className="space-y-6">
                <div className="bg-white rounded-xl p-6 border border-primary/20">
                  <div className="flex items-center gap-3 mb-2">
                    <DollarSign className="h-6 w-6 text-primary" />
                    <span className="text-3xl font-bold text-primary">$150K</span>
                  </div>
                  <p className="text-gray-700 font-semibold">Additional sales (3 months)</p>
                  <p className="text-gray-600 text-sm mt-1">From recovered carts</p>
                </div>

                <div className="bg-white rounded-xl p-6 border border-primary/20">
                  <div className="flex items-center gap-3 mb-2">
                    <Users className="h-6 w-6 text-primary" />
                    <span className="text-3xl font-bold text-primary">72%</span>
                  </div>
                  <p className="text-gray-700 font-semibold">Cart recovery rate</p>
                  <p className="text-gray-600 text-sm mt-1">Industry average is 8-15%</p>
                </div>

                <div className="bg-white rounded-xl p-6 border border-primary/20">
                  <div className="flex items-center gap-3 mb-2">
                    <TrendingUp className="h-6 w-6 text-primary" />
                    <span className="text-3xl font-bold text-primary">+28%</span>
                  </div>
                  <p className="text-gray-700 font-semibold">Increase in AOV</p>
                  <p className="text-gray-600 text-sm mt-1">From AI recommendations</p>
                </div>
              </div>

              <div className="mt-6 p-4 bg-primary/10 rounded-lg border border-primary/20">
                <p className="text-center font-bold text-gray-800">
                  Paid for itself in 18 days
                </p>
              </div>
            </div>

            {/* Custom AI Results */}
            <div className="bg-gradient-to-br from-primary/5 to-accent2/5 rounded-2xl p-8 border-2 border-primary/20 shadow-lg hover:shadow-xl transition-all">
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-2xl font-bold text-gray-900">Custom AI</h3>
                <div className="bg-primary/10 p-3 rounded-xl">
                  <TrendingUp className="h-8 w-8 text-primary" />
                </div>
              </div>

              <p className="text-gray-700 mb-6 font-semibold">
                B2B SaaS company, complex sales cycle
              </p>

              <div className="space-y-6">
                <div className="bg-white rounded-xl p-6 border border-primary/20">
                  <div className="flex items-center gap-3 mb-2">
                    <DollarSign className="h-6 w-6 text-primary" />
                    <span className="text-3xl font-bold text-primary">$420K</span>
                  </div>
                  <p className="text-gray-700 font-semibold">Additional pipeline (Year 1)</p>
                  <p className="text-gray-600 text-sm mt-1">From qualified leads</p>
                </div>

                <div className="bg-white rounded-xl p-6 border border-primary/20">
                  <div className="flex items-center gap-3 mb-2">
                    <Users className="h-6 w-6 text-primary" />
                    <span className="text-3xl font-bold text-primary">67%</span>
                  </div>
                  <p className="text-gray-700 font-semibold">Of inquiries automated</p>
                  <p className="text-gray-600 text-sm mt-1">Freeing up sales team</p>
                </div>

                <div className="bg-white rounded-xl p-6 border border-primary/20">
                  <div className="flex items-center gap-3 mb-2">
                    <Clock className="h-6 w-6 text-primary" />
                    <span className="text-3xl font-bold text-primary">4.5 hrs</span>
                  </div>
                  <p className="text-gray-700 font-semibold">Saved per day</p>
                  <p className="text-gray-600 text-sm mt-1">In manual qualification</p>
                </div>
              </div>

              <div className="mt-6 p-4 bg-primary/10 rounded-lg border border-primary/20">
                <p className="text-center font-bold text-gray-800">
                  3X increase in qualified demos
                </p>
              </div>
            </div>
          </div>

          {/* Bottom Stats Bar */}
          <div className="bg-gradient-to-r from-primary to-accent2 rounded-2xl shadow-xl p-8 md:p-12 text-white">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-8 text-center">
              <div>
                <div className="text-4xl md:text-5xl font-bold mb-2 text-secondary">$2.3M+</div>
                <p className="text-white font-semibold">Total revenue generated</p>
                <p className="text-gray-200 text-sm mt-1">Across all clients (last 12 months)</p>
              </div>

              <div className="border-t md:border-t-0 md:border-l border-white/30 pt-6 md:pt-0">
                <div className="text-4xl md:text-5xl font-bold mb-2 text-secondary">15,000+</div>
                <p className="text-white font-semibold">Leads captured</p>
                <p className="text-gray-200 text-sm mt-1">That would have been lost</p>
              </div>

              <div className="border-t md:border-t-0 md:border-l border-white/30 pt-6 md:pt-0">
                <div className="text-4xl md:text-5xl font-bold mb-2 text-secondary">24/7</div>
                <p className="text-white font-semibold">Always working</p>
                <p className="text-gray-200 text-sm mt-1">No vacation, no sick days</p>
              </div>

              <div className="border-t md:border-t-0 md:border-l border-white/30 pt-6 md:pt-0">
                <div className="text-4xl md:text-5xl font-bold mb-2 text-secondary">98%</div>
                <p className="text-white font-semibold">Client satisfaction</p>
                <p className="text-gray-200 text-sm mt-1">Would recommend to others</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HomeRealResultsSection;
